baseURL: "https://dridani.my.id"
title: "DRIDANI BLOG"
languageCode: id-ID
defaultContentLanguage: id
paginate: 5
summaryLength: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true
mainsections: ["posts"]

module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod

outputs:
  home:
    - HTML
    - RSS
    - JSON

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "DRIDANI BLOG"
  description: "Blog pribadi yang berisikian informasi, dokumentasi, dan ulasan"
  keywords: ["DRIDANI", "Blog", "Android", "Aplikasi", "Review", "Tutorial"]
  author: "Dony Ridani"
  DateFormat: "Monday, 02 Jan 2006"

  defaultTheme: auto
  disableThemeToggle: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowPageNums: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  analytics:
    google:
      SiteVerificationTag: ""

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"

  label:
    text: "DRIDANI BLOG"

  homeInfoParams:
    Title: "Hai! Saya Dony"
    Content: "Selamat datang di blog pribadi saya. Blog ini adalah tempat saya mendokumentasikan hasil belajar serta hal-hal gabut yang saya lakukan."

  socialIcons:
    - name: facebook
      url: "https://facebook.com/dony.ridani"
    - name: instagram
      url: "https://instagram.com/dony.ridani"
    - name: telegram
      url: "https://t.me/iminterfacing"

  cover:
    hidden: true
    hiddenInList: true  
    hiddenInSingle: true
    responsiveImages: false

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - name: Tentang
      url: "/tentang"
      weight: 5
    - name: Kategori
      url: "/kategori"
      weight: 10
    - name: Cari
      url: "/cari"
      weight: 20

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

permalinks:
  posts: "/:slug/"
  page: "/:slug/"
  tags: "/tag/:slug/"
  categories: "/kategori/:slug/"
